"""empty message

Revision ID: f485e1723a23
Revises: a5d2cec703e3
Create Date: 2020-02-14 18:15:36.881297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f485e1723a23'
down_revision = 'a5d2cec703e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_authenticated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_authenticated')
    op.drop_column('user', 'is_anonymous')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
